#!/usr/bin/env node
// Regenerates words.data.js and leaves.data.js in the repo root: base64
// copies of the gzipped assets, wrapped in a script file. When index.html
// is opened straight from disk (file://), fetch() cannot read sibling
// files, but an injected <script> tag can — game.js loads these as a
// fallback and inflates them with DecompressionStream. Served over HTTP
// the fallback never runs and these files are never downloaded.
//
// Re-run after any change to words.txt.gz or leaves-w.txt.gz.
'use strict';

const fs = require('fs');
const path = require('path');

const repo = path.resolve(__dirname, '..');

for (const [gz, out, name] of [
  ['words.txt.gz', 'words.data.js', 'WORDS_GZ_B64'],
  ['leaves-w.txt.gz', 'leaves.data.js', 'LEAVES_W_B64'],
  ['endgame-leaves.json.gz', 'endgame-leaves.data.js', 'EG_LEAVES_B64'],
]) {
  const gzPath = path.join(repo, gz);
  if (!fs.existsSync(gzPath)) {
    console.log(gz + ' not found — skipping ' + out);
    continue;
  }
  const b64 = fs.readFileSync(gzPath).toString('base64');
  fs.writeFileSync(path.join(repo, out),
    '// Generated by tools/build-data-js.js from ' + gz + ' — do not edit.\n' +
    'var ' + name + ' = ' + JSON.stringify(b64) + ';\n');
  console.log(out + ': ' + Math.round(b64.length / 1024) + ' KB');
}
